# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: ssh
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# Aliases allow you to create nicknames for gh commands
aliases:
    live: "api --hostname github.tools.sap graphql -f query='\n  mutation {\n    changeUserStatus(input:{\n      message: \"$1\",\n      emoji: \"\U0001F4FA\"\n    }) {\n      status { message, emoji }\n    }\n  }'\n"
    assigned: issue list --assignee i347491
    authswitch: '!bash -c "pass show $1/$2/pat | gh auth login --with-token && gh auth status 2> >(grep \"Logged in to $1\")"'
